name: Check Build

on: [ push, pull_request ]

jobs:

  build:

    strategy:
      matrix:
        php: [ '8.0' ]
        dependencies: [ 'lowest', 'highest' ]

    runs-on: ubuntu-latest

    name: 'PHP ${{ matrix.php }} with ${{ matrix.dependencies }} dependencies'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-progress --prefer-lowest
        if: "${{ matrix.dependencies == 'lowest' }}"

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-progress
        if: "${{ matrix.dependencies == 'highest' }}"

      - name: Static analysis
        run: |
          composer check-deps
          composer cs-check
          composer psalm
          composer phpstan -- --no-progress

      - name: Tests
        run: |
          composer phpunit
          composer infection
